USE BBDD_EmilianoDelia

TRUNCATE TABLE DRUG_STRENGTH

BULK INSERT DRUG_STRENGTH

/* TABLE SHOULD END UP WITH 2,981,807 TOTAL ROWS */

FROM 'E:\Archivos BULK INSERT\DRUG_STRENGTH.csv'

	WITH (
		FORMAT ='CSV', 
		CODEPAGE = '65001', -- UTF-8 codepage
		FIRSTROW = 2,
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n',
		TABLOCK, 
		BATCHSIZE=250000,
		KEEPNULLS,
		MAXERRORS=250000
);  

SELECT COUNT(*) FROM BBDD_EMILIANODELIA.DBO.DRUG_STRENGTH;