USE BBDD_EmilianoDelia

BULK INSERT CONCEPT_RELATIONSHIP

/* TABLE SHOULD END UP WITH 52,897,752 TOTAL ROWS */

FROM 'E:\Archivos BULK INSERT\CONCEPT_RELATIONSHIP.csv'

	WITH (
		FORMAT ='CSV', 
		CODEPAGE = '65001', -- UTF-8 codepage
		FIRSTROW = 2,
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n',
		TABLOCK, 
		BATCHSIZE=250000,
		KEEPNULLS, 
		MAXERRORS=250000
);  

SELECT COUNT(*) AS TOTAL_ROWS FROM CONCEPT_RELATIONSHIP;