USE BBDD_EmilianoDelia

/* DROP ALL CONSTRAINTS FROM ALL SCHEMA */

DECLARE @TableName NVARCHAR(MAX);
DECLARE @ConstraintName NVARCHAR(MAX);
DECLARE @DropConstraintSql NVARCHAR(MAX);

DECLARE TableCursor CURSOR FOR
SELECT t.name AS TableName, fk.name AS ConstraintName
FROM sys.tables t
JOIN sys.foreign_keys fk ON t.object_id = fk.parent_object_id

OPEN TableCursor;
FETCH NEXT FROM TableCursor INTO @TableName, @ConstraintName;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @DropConstraintSql = 'ALTER TABLE ' + QUOTENAME(@TableName) + ' DROP CONSTRAINT ' + QUOTENAME(@ConstraintName);
    EXEC(@DropConstraintSql);
    
    FETCH NEXT FROM TableCursor INTO @TableName, @ConstraintName;
END

CLOSE TableCursor;
DEALLOCATE TableCursor;

/********************************************************************************************************/
/**** SINCE WE UPLOADED THE FOLLOWING REFERENCE TABLES FROM A CSV FILE WE MUST SET THE PKs MANUALLY ****/
/********************************************************************************************************/

IF NOT EXISTS (
    SELECT 1 FROM sys.key_constraints 
    WHERE type = 'PK' 
    AND parent_object_id = OBJECT_ID('CONCEPT')
)
BEGIN
	ALTER TABLE CONCEPT 
	ADD CONSTRAINT PK_CONCEPT_ID
	PRIMARY KEY (CONCEPT_ID)
END;

IF NOT EXISTS (
    SELECT 1 
    FROM sys.key_constraints 
    WHERE type = 'PK' 
    AND parent_object_id = OBJECT_ID('CONCEPT_CLASS')
)
BEGIN
	ALTER TABLE CONCEPT_CLASS
	ADD CONSTRAINT PK_CONCEPT_CLASS_ID
	PRIMARY KEY (CONCEPT_CLASS_ID)
END;

IF NOT EXISTS (
    SELECT 1 
    FROM sys.key_constraints 
    WHERE type = 'PK' 
    AND parent_object_id = OBJECT_ID('DOMAIN')
)	
BEGIN 
	ALTER TABLE DOMAIN
	ADD CONSTRAINT PK_DOMAIN_ID
	PRIMARY KEY (DOMAIN_ID)
END;

IF NOT EXISTS (
    SELECT 1 
    FROM sys.key_constraints 
    WHERE type = 'PK' 
    AND parent_object_id = OBJECT_ID('VOCABULARY')
)	
BEGIN
	ALTER TABLE VOCABULARY
	ADD CONSTRAINT PK_VOCABULARY_ID
	PRIMARY KEY (VOCABULARY_ID)
END;

IF NOT EXISTS (
    SELECT 1 
    FROM sys.key_constraints 
    WHERE type = 'PK' 
    AND parent_object_id = OBJECT_ID('RELATIONSHIP')
)	
BEGIN
	ALTER TABLE RELATIONSHIP
	ADD CONSTRAINT PK_RELATIONSHIP_ID
	PRIMARY KEY (RELATIONSHIP_ID)
END;

/***********   CONCEPT  ***********/
IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_DOMAIN_ID')
	ALTER TABLE CONCEPT 
	ADD CONSTRAINT FK_DOMAIN_ID 
	FOREIGN KEY (DOMAIN_ID) 
	REFERENCES DOMAIN(DOMAIN_ID);

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_VOCABULARY_ID')
    ALTER TABLE CONCEPT 
	ADD CONSTRAINT FK_VOCABULARY_ID 
	FOREIGN KEY (VOCABULARY_ID) 
	REFERENCES VOCABULARY(VOCABULARY_ID);

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_CONCEPT_CLASS_ID')
ALTER TABLE CONCEPT 
	ADD CONSTRAINT FK_CONCEPT_CLASS_ID 
	FOREIGN KEY (CONCEPT_CLASS_ID) 
	REFERENCES CONCEPT_CLASS(CONCEPT_CLASS_ID);

/***********   CONCEPT ANCESTOR  ***********/
-- THIS TABLE DOES NOT HOLD A PRIMARY KEY --
/*******************************************/

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_ANCESTOR_CONCEPT_ID')
	ALTER TABLE CONCEPT_ANCESTOR
	ADD CONSTRAINT FK_ANCESTOR_CONCEPT_ID
	FOREIGN KEY (ANCESTOR_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID);

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_DESCENDAND_CONCEPT_ID')
	ALTER TABLE CONCEPT_ANCESTOR
	ADD CONSTRAINT FK_DESCENDAND_CONCEPT_ID
	FOREIGN KEY (DESCENDANT_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID);

/***********   CONCEPT CLASS  ***********/

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_CONCEPT_CLASS_CONCEPT_ID')
	ALTER TABLE CONCEPT_CLASS
	ADD CONSTRAINT FK_CONCEPT_CLASS_CONCEPT_ID
	FOREIGN KEY (CONCEPT_CLASS_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

/***********   CONCEPT RELATIONSHIP  ***********/
-- THIS TABLE DOES NOT HOLD A PRIMARY KEY --
-- INFO WAS TOO BIG FOR A SINGLE IMPORT  --
/*******************************************/

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_CONCEPT_ID_1')
	ALTER TABLE CONCEPT_RELATIONSHIP
	ADD CONSTRAINT FK_CONCEPT_ID_1
	FOREIGN KEY (CONCEPT_ID_1)
	REFERENCES CONCEPT(CONCEPT_ID)

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_CONCEPT_ID_2')
	ALTER TABLE CONCEPT_RELATIONSHIP
	ADD CONSTRAINT FK_CONCEPT_ID_2
	FOREIGN KEY (CONCEPT_ID_2)
	REFERENCES CONCEPT(CONCEPT_ID)

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_RELATIONSHIP_ID')
	ALTER TABLE CONCEPT_RELATIONSHIP
	ADD CONSTRAINT FK_RELATIONSHIP_ID
	FOREIGN KEY (RELATIONSHIP_ID)
	REFERENCES RELATIONSHIP(RELATIONSHIP_ID)

/***********   CONCEPT SYNONYM  ***********/
-- THIS TABLE DOES NOT HOLD A PRIMARY KEY --
/*******************************************/

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_CONCEPT_ID_CON_SYNONYM')
ALTER TABLE CONCEPT_SYNONYM
	ADD CONSTRAINT FK_CONCEPT_ID_CON_SYNONYM
	FOREIGN KEY (CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_LANGUAGE_CONCEPT_ID')
	ALTER TABLE CONCEPT_SYNONYM
	ADD CONSTRAINT FK_LANGUAGE_CONCEPT_ID
	FOREIGN KEY (LANGUAGE_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

/***********   DOMAIN  ***********/
IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_DOMAIN_CONCEPT_ID')
	ALTER TABLE DOMAIN
	ADD CONSTRAINT FK_DOMAIN_CONCEPT_ID
	FOREIGN KEY (DOMAIN_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

/***********   RELATIONSHIP  ***********/
IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_RELATIONSHIP_CONCEPT_ID')
	ALTER TABLE RELATIONSHIP
	ADD CONSTRAINT FK_RELATIONSHIP_CONCEPT_ID
	FOREIGN KEY (RELATIONSHIP_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

/***********   VOCABULARY  ***********/
IF NOT EXISTS (SELECT 1 FROM SYS.INDEXES WHERE NAME = 'FK_VOCABULARY_CONCEPT_ID')
	ALTER TABLE VOCABULARY 
	ADD CONSTRAINT FK_VOCABULARY_CONCEPT_ID
	FOREIGN KEY (VOCABULARY_CONCEPT_ID)
	REFERENCES CONCEPT(CONCEPT_ID)

/***********************************************************************/
/***********   CREATE INDEXES FOR STANDARDIZED VOCABULARIES  ***********/
/***********************************************************************/

-- NOT NECESSARY TO CREATE CLUSTERED INDEX IN SOME TABLES 
-- ONCE A PK IS CREATED A CLUSTERED INDEX IS AUTOMATICALLY CREATED 

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_code')
    CREATE INDEX idx_concept_code ON BBDD_EmilianoDelia.dbo.concept (concept_code ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_vocabluary_id')
    CREATE INDEX idx_concept_vocabluary_id ON BBDD_EmilianoDelia.dbo.concept (vocabulary_id ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_domain_id')
    CREATE INDEX idx_concept_domain_id ON BBDD_EmilianoDelia.dbo.concept (domain_id ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_class_id')
    CREATE INDEX idx_concept_class_id ON BBDD_EmilianoDelia.dbo.concept (concept_class_id ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_relationship_id_2')
    CREATE INDEX idx_concept_relationship_id_2 ON BBDD_EmilianoDelia.dbo.concept_relationship (concept_id_2 ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_relationship_id_3')
    CREATE INDEX idx_concept_relationship_id_3 ON BBDD_EmilianoDelia.dbo.concept_relationship (relationship_id ASC);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'idx_concept_ancestor_id_2')
    CREATE INDEX idx_concept_ancestor_id_2 ON BBDD_EmilianoDelia.dbo.concept_ancestor (descendant_concept_id ASC);


/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********   FK CONSTRAINTS FOR CLINICAL DATA  ***********/
/***********************************************************/
/***********************************************************/
/***********************************************************/


/***********************************************/
/***************      PERSON       *************/
/***********************************************/

ALTER TABLE PERSON 
ADD CONSTRAINT FK_GENDER_CONCEPT_ID
FOREIGN KEY (GENDER_CONCEPT_ID) 
REFERENCES CONCEPT(CONCEPT_ID);

/***********************************************/
/***********   CARE SITE & LOCATION  ***********/
/***********************************************/

ALTER TABLE CARE_SITE
ADD CONSTRAINT FK_PLACE_OF_SERVICE_CONCEPT_ID 
FOREIGN KEY  (PLACE_OF_SERVICE_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE CARE_SITE
ADD CONSTRAINT FK_LOCATION_ID_CARE_SITE
FOREIGN KEY  (LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID)

ALTER TABLE LOCATION
ADD CONSTRAINT FK_COUNTRY_CONCEPT_ID
FOREIGN KEY (COUNTRY_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

/***********************************************/
/***********   CONDITION OCCURRENCE  ***********/
/***********************************************/

ALTER TABLE CONDITION_OCCURRENCE 
ADD CONSTRAINT FK_PERSON_ID_CONDITION_OCCURRENCE
FOREIGN KEY (PERSON_ID) 
REFERENCES PERSON(PERSON_ID);

ALTER TABLE CONDITION_OCCURRENCE 
ADD CONSTRAINT FK_CONDITION_STATUS_CONCEPT_ID
FOREIGN KEY (condition_status_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE CONDITION_OCCURRENCE 
ADD CONSTRAINT FK_CONDITION_TYPE_CONCEPT_ID_CONDITION_OCCURRENCE
FOREIGN KEY (CONDITION_TYPE_CONCEPT_ID) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE CONDITION_OCCURRENCE 
ADD CONSTRAINT FK_VISIT_OCCURRENCE_ID_CONDITION_OCCURRENCE
FOREIGN KEY (visit_occurrence_id) 
REFERENCES VISIT_OCCURRENCE(visit_occurrence_id);

ALTER TABLE CONDITION_OCCURRENCE 
ADD CONSTRAINT FK_PROVIDER_ID_CONDITION_OCCURRENCE
FOREIGN KEY (PROVIDER_ID) 
REFERENCES PROVIDER(PROVIDER_ID);

/********************************/
/***********   DEATH  ***********/
/********************************/

ALTER TABLE DEATH 
ADD CONSTRAINT FK_PERSON_ID_DEATH
FOREIGN KEY (PERSON_ID) 
REFERENCES PERSON(PERSON_ID);

ALTER TABLE DEATH 
ADD CONSTRAINT FK_DEATH_TYPE_CONCEPT_ID
FOREIGN KEY (death_type_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE DEATH 
ADD CONSTRAINT FK_DEATH_CAUSE_CONCEPT_ID
FOREIGN KEY (cause_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE DEATH 
ADD CONSTRAINT FK_DEATH_CAUSE_SOURCE_CONCEPT_ID
FOREIGN KEY (cause_source_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

/*****************************************/
/***********   DRUG EXPOSURE  ***********/
/*****************************************/

ALTER TABLE DRUG_EXPOSURE 
ADD CONSTRAINT FK_PERSON_ID_DRUG_EXPOSURE
FOREIGN KEY (PERSON_ID) 
REFERENCES PERSON(PERSON_ID);

ALTER TABLE DRUG_EXPOSURE 
ADD CONSTRAINT FK_DRUG_CONCEPT_ID
FOREIGN KEY (DRUG_CONCEPT_ID) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE DRUG_EXPOSURE 
ADD CONSTRAINT FK_DRUG_TYPE_CONCEPT_ID
FOREIGN KEY (DRUG_TYPE_CONCEPT_ID) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE DRUG_EXPOSURE 
ADD CONSTRAINT FK_ROUTE_CONCEPT_ID
FOREIGN KEY (route_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE DRUG_EXPOSURE 
ADD CONSTRAINT FK_VISIT_OCC_DRUG_EXPOSURE
FOREIGN KEY (VISIT_OCCURRENCE_ID) 
REFERENCES VISIT_OCCURRENCE(VISIT_OCCURRENCE_ID);

/*****************************************/
/***********   OBSERVATION  **************/
/*****************************************/

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_PERSON_ID_OBSERVATION
FOREIGN KEY (PERSON_ID) 
REFERENCES PERSON(PERSON_ID);

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_observation_concept_id
FOREIGN KEY (observation_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_observation_type_concept_id
FOREIGN KEY (observation_type_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_VALUE_AS_CONCEPT_ID
FOREIGN KEY (value_as_concept_id) 
REFERENCES CONCEPT(CONCEPT_ID);

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_PROVIDER_ID_OBSERVATION
FOREIGN KEY (PROVIDER_ID) 
REFERENCES PROVIDER(PROVIDER_ID);

ALTER TABLE OBSERVATION
ADD CONSTRAINT FK_VISIT_OCCURRENCE_ID_OBSERVATION
FOREIGN KEY (VISIT_OCCURRENCE_ID) 
REFERENCES VISIT_OCCURRENCE(VISIT_OCCURRENCE_ID);

/*****************************************/
/******** OBSERVATION PERIOD  ***********/
/***************************************/

ALTER TABLE OBSERVATION_PERIOD
ADD CONSTRAINT FK_PERSON_ID_OBSERVATION_PERIOD
FOREIGN KEY (PERSON_ID) 
REFERENCES PERSON(PERSON_ID);

ALTER TABLE OBSERVATION_PERIOD
ADD CONSTRAINT FK_PERIOD_TYPE_CONCEPT_ID_OBS_PERIOD
FOREIGN KEY (PERIOD_TYPE_CONCEPT_ID) 
REFERENCES CONCEPT(CONCEPT_ID);

/*****************************************/
/********  PROCEDURE OCCURRENCE  ********/
/***************************************/

ALTER TABLE PROCEDURE_OCCURRENCE
ADD CONSTRAINT FK_PERSON_ID_PROC_OCCURRENCE
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE PROCEDURE_OCCURRENCE
ADD CONSTRAINT FK_PROCEDURE_CONCEPT_ID
FOREIGN KEY (PROCEDURE_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE PROCEDURE_OCCURRENCE
ADD CONSTRAINT FK_PROCEDURE_TYPE_CONCEPT_ID
FOREIGN KEY (PROCEDURE_TYPE_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE PROCEDURE_OCCURRENCE
ADD CONSTRAINT FK_PROVIDER_ID_PROC_OCCURRENCE
FOREIGN KEY (PROVIDER_ID)
REFERENCES PROVIDER(PROVIDER_ID)

ALTER TABLE PROCEDURE_OCCURRENCE
ADD CONSTRAINT FK_VISIT_OCC_ID_PROC_OCC
FOREIGN KEY (VISIT_OCCURRENCE_ID)
REFERENCES VISIT_OCCURRENCE(VISIT_OCCURRENCE_ID)

/*****************************************/
/************    PROVIDER  **************/
/***************************************/

ALTER TABLE PROVIDER
ADD CONSTRAINT FK_SPECIALTY_CONCEPT_ID
FOREIGN KEY (SPECIALTY_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

/*****************************************/
/********    VISIT DETAIL   *************/
/***************************************/

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_PERSON_ID_VISIT_DETAIL
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_VISIT_DETAIL_CONCEPT_ID_VISIT_DETAIL
FOREIGN KEY (visit_detail_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_VISIT_DETAIL_TYPE_CONCEPT_ID_VISIT_DETAIL
FOREIGN KEY (visit_detail_type_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_PROVIDER_ID_VISIT_DETAIL
FOREIGN KEY (PROVIDER_ID)
REFERENCES PROVIDER(PROVIDER_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_CARE_SITE_ID_VISIT_DETAIL
FOREIGN KEY (care_site_id)
REFERENCES CARE_SITE(CARE_SITE_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_VISIT_DETAIL_SOURCE_CONCEPT_ID_VISIT_DETAIL
FOREIGN KEY (visit_detail_source_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_ADMITTED_FROM_CONCEPT_ID_VISIT_DETAIL
FOREIGN KEY (admitted_from_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_DISCHARGED_TO_CONCEPT_ID
FOREIGN KEY (discharged_to_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_DETAIL
ADD CONSTRAINT FK_VISIT_OCCURRENCE_ID_VISIT_DETAIL
FOREIGN KEY (visit_occurrence_id)
REFERENCES visit_occurrence(visit_occurrence_id)

/*****************************************/
/********    VISIT_OCCURRENCE   *********/
/***************************************/

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_PERSON_ID_VISIT_OCCURRENCE
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_VISIT_CONCEPT_ID_VISIT_OCCURRENCE
FOREIGN KEY (VISIT_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_VISIT_TYPE_CONCEPT_ID_VISIT_OCCURRENCE
FOREIGN KEY (VISIT_TYPE_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_PROVIDER_ID_VISIT_OCCURRENCE
FOREIGN KEY (PROVIDER_ID)
REFERENCES PROVIDER(PROVIDER_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_CARE_SITE_ID_VISIT_OCCURRENCE
FOREIGN KEY (CARE_SITE_ID)
REFERENCES CARE_SITE(CARE_SITE_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_ADMITTED_FROM_CONCEPT_ID_VISIT_OCCURRENCE
FOREIGN KEY (ADMITTED_FROM_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE VISIT_OCCURRENCE
ADD CONSTRAINT FK_DISCHARGED_TO_CONCEPT_ID_VISIT_OCCURRENCE
FOREIGN KEY (DISCHARGED_TO_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

/*****************************************/
/********    cdm_source   *********/
/***************************************/
--condition_era 
--dose_era
--drug_era
--visit_detail
--meta_data
--measurement

/*****************************************/
/********    CONDITION ERA   *********/
/***************************************/

ALTER TABLE CONDITION_ERA
ADD CONSTRAINT FK_PERSON_ID_CONDITION_ERA
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE CONDITION_ERA
ADD CONSTRAINT FK_CONDITION_CONCEPT_ID_CONDITION_ERA
FOREIGN KEY (CONDITION_CONCEPT_ID)
REFERENCES CONCEPT(CONCEPT_ID)

/********************************/
/********    DOSE ERA   *********/
/********************************/

ALTER TABLE DOSE_ERA
ADD CONSTRAINT FK_PERSON_ID_DOSE_ERA
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE DOSE_ERA
ADD CONSTRAINT FK_DRUG_CONCEPT_ID_DOSE_ERA
FOREIGN KEY (drug_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE DOSE_ERA
ADD CONSTRAINT FK_UNIT_CONCEPT_ID_DOSE_ERA
FOREIGN KEY (unit_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

/***************************************/
/************    METADATA  *************/
/***************************************/
ALTER TABLE METADATA
ADD CONSTRAINT FK_METADATA_CONCEPT_ID
FOREIGN KEY (metadata_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE METADATA
ADD CONSTRAINT FK_METADATA_TYPE_CONCEPT_ID
FOREIGN KEY (metadata_type_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE METADATA
ADD CONSTRAINT FK_METADATA_VALUE_AS_CONCEPT_ID
FOREIGN KEY (value_as_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

/****************************************/
/************    EPISODE EVENT  *********/
/****************************************/
ALTER TABLE EPISODE_EVENT
ADD CONSTRAINT FK_EPISODE_ID_EPISODE_EVENT 
FOREIGN KEY (episode_id)
REFERENCES EPISODE(EPISODE_ID)

ALTER TABLE EPISODE_EVENT
ADD CONSTRAINT FK_EPISODE_EVENT_FIELD_CONCEPT_ID 
FOREIGN KEY (episode_event_field_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

/***************************************/
/************    EPISODE   *************/
/***************************************/
ALTER TABLE EPISODE 
ADD CONSTRAINT FK_PERSON_ID_EPISODE
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID)

ALTER TABLE EPISODE 
ADD CONSTRAINT FK_EPISODE_CONCEPT_ID
FOREIGN KEY (episode_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE EPISODE
ADD CONSTRAINT FK_EPISODE_OBJECT_CONCEPT_ID
FOREIGN KEY (episode_object_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE EPISODE
ADD CONSTRAINT FK_EPISODE_TYPE_CONCEPT_ID
FOREIGN KEY (episode_type_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)

ALTER TABLE EPISODE 
ADD CONSTRAINT FK_EPISODE_SOURCE_CONCEPT_ID
FOREIGN KEY (episode_source_concept_id)
REFERENCES CONCEPT(CONCEPT_ID)